### PR TITLE
fix: Fixed Index out of bounds issue with network ordinal

### PR DESCRIPTION
**Pull request by mathias21**
Added Goerli support
Added tests for Goerli
All tests passed (50 of 50 tests passed)

### CODE REVIEW

**Comment by mathias21** [comment]
Hey @craigraw 
Let me know if this fits. We have the need to use Goerli so I've added support for that. Following [this](https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-007-hdkey.md) to specify Goerli value

**Comment by craigraw** [comment]
Although I have no need of Ethereum values myself, I've no particular problem adding support for what is defined in the specification.

Quite a few of the changes proposed simply add spaces before brackets, probably due to automatic code formatting - could these be removed to simplify and keep the code style consistent?

**Comment by mathias21** [comment]
> Although I have no need of Ethereum values myself, I've no particular problem adding support for what is defined in the specification.
> 
> Quite a few of the changes proposed simply add spaces before brackets, probably due to automatic code formatting - could these be removed to simplify and keep the code style consistent?

Sure, I will remove them and push a new commit.

**Comment by craigraw** [comment]
Thanks!

**Pull request merged**
