### PR TITLE
feat(Crypto-sskr): added crypto-sskr UR support

### PR DESCRIPTION
**Pull request by mathias21**
## Description
- Added Crypto-sskr registry item
- Added tests for Crypto-sskr
- All tests passes

### CODE REVIEW

**Comment by mathias21** [comment]
@craigraw let me know if this is fine, we will make use of the SSKR UR format in our project.

**Comment by craigraw** [comment]
LGTM. I'll publish a new release with these changes.

**Comment by craigraw** [comment]
Hummingbird v1.6.6 has been published and should appear in Maven Central soon.

**Comment by mathias21** [comment]
> Hummingbird v1.6.6 has been published and should appear in Maven Central soon.

Thanks @craigraw!

**Pull request merged**
